version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: entchat-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: entchat-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
